name: ci

on:
  workflow_call:
    inputs:
      pubspec:
        default: '0'
        required: true
        type: string
      target:
        default: '0'
        required: true
        type: string

jobs:
  pre:
    runs-on: ubuntu-24.04
    outputs:
      pubspec: ${{ inputs.pubspec }}
    steps:
      - run: echo "Bypass GitHub Action Restriction"
  ready:
    needs:
      - pre
    uses: LaoWangFantasy/Flutter-Actions/.github/workflows/get-version.yml@master
    with:
      pub_path: ${{ needs.pre.outputs.pubspec }}
  tag:
    needs:
      - ready
    uses: LaoWangFantasy/Flutter-Actions/.github/workflows/create-tag.yml@master
    with:
      version: ${{ needs.ready.outputs.version }}
  release:
    needs:
      - tag
    uses: LaoWangFantasy/Flutter-Actions/.github/workflows/create-release.yml@master
    with:
      tag: ${{ needs.tag.outputs.tag }}
      note: "add release for ${{ needs.tag.outputs.tag }}"
  push:
    needs:
      - release
    uses: LaoWangFantasy/Flutter-Actions/.github/workflows/create-binary.yml@master
    with:
      tag: ${{ needs.release.outputs.pushed_tag }}
      target: ${{ inputs.target }}