name: create-tag

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_call:
    inputs:
      version:
        default: '0'
        required: true
        type: string
    outputs:
      tag:
        description: "Pushed tag version"
        value: ${{ jobs.create-tag.outputs.tag }}

jobs:
  create-tag:
    runs-on: ubuntu-24.04
    outputs:
      tag: ${{ steps.push.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - 
        id: check_tag
        run: |
          echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          if git rev-parse "${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi
      - 
        if: env.TAG_EXISTS == 'true'
        id: modify_tag
        run: |
          new_version="${{ inputs.version }}-build-${{ github.run_number }}"
          echo "VERSION=$new_version" >> $GITHUB_ENV
      - 
        id: push
        run: |
          git tag ${{ env.VERSION }} && git push --tags
          echo tag=${{ env.VERSION }} >> $GITHUB_OUTPUT
        name: Push Tag
        shell: bash
