name: create-binary

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_call:
    inputs:
      tag:
        default: '0'
        required: true
        type: string
      target:
        default: 'web'
        required: true
        type: string
jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - 
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}"
          PREFIX="build/${{ inputs.target }}"
          BIN="${{ inputs.target }}.tar.gz"
          BINN="$REPO_NAME-$BIN"
          tar -czf $BIN $PREFIX
          mv $BIN $BINN
          gh release upload ${{ inputs.tag }} $BINN
        shell: bash
        name: Upload